sources += files(
    'pdg/core/assert.cpp',
    'pdg/core/assert_internal.cpp',
    'pdg/core/allocator.cpp',
    'pdg/core/allocator_utils.cpp',
    'pdg/core/dumb_allocator.cpp',
    'pdg/core/linear_allocator.cpp',
    'pdg/core/stack_allocator.cpp',
    'pdg/core/type_info.cpp',
    'pdg/core/ref_counted.cpp',
    'pdg/core/string_hash.cpp',
    'pdg/core/fragile_bool.cpp',
    'pdg/core/string_utils.cpp',
)

